# config/agents_control.yaml
# Controle Global de Agentes

active_agents:
  - irpj_csll

global_config:
  default_temperature: 0.7
  default_max_tokens: 1200
  enable_fact_checking: true
  enable_rag: false
  log_level: INFO
